DROP TABLE IF EXISTS `growatt`;

-- New table schema matching updated register list
CREATE TABLE growatt (
  id INT(11) NOT NULL AUTO_INCREMENT,
  inverter_id INT(11) NOT NULL,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP(),

  -- Power input, voltage and current
  pv1_voltage FLOAT,
  pv2_voltage FLOAT,
  pv1_charge_power FLOAT,
  pv2_charge_power FLOAT,
  output_active_power FLOAT,
  output_apparent_power FLOAT,
  ac_charge_power FLOAT,
  ac_charge_apparent_power FLOAT,
  ac_input_power FLOAT,
  ac_input_va FLOAT,

  -- Temperatures
  inverter_temp FLOAT,
  dcdc_temp FLOAT,
  buck1_temp FLOAT,
  buck2_temp FLOAT,

  -- Currents
  buck1_current FLOAT,
  buck2_current FLOAT,
  output_current FLOAT,
  inverter_current FLOAT,
  ac_charge_current FLOAT,
  ac_discharge_watt FLOAT,
  ac_discharge_va FLOAT,
  bat_discharge_watt FLOAT,
  bat_discharge_va FLOAT,
  battery_watt FLOAT,

  -- Voltages and frequency
  battery_voltage FLOAT,
  bus_voltage FLOAT,
  grid_voltage FLOAT,
  line_frequency FLOAT,
  output_voltage FLOAT,
  output_frequency FLOAT,
  dc_output_voltage FLOAT,
  battery_port_voltage FLOAT,
  battery_bus_voltage FLOAT,

  -- Energy
  pv1_energy_today FLOAT,
  pv1_energy_total FLOAT,
  pv2_energy_today FLOAT,
  pv2_energy_total FLOAT,
  ac_charge_energy_today FLOAT,
  ac_charge_energy_total FLOAT,
  bat_discharge_energy_today FLOAT,
  bat_discharge_energy_total FLOAT,
  ac_discharge_energy_today FLOAT,
  ac_discharge_energy_total FLOAT,

  -- BMS 1
  bms_soc INT,
  bms_battery_volt FLOAT,
  bms_battery_curr FLOAT,
  bms_battery_temp FLOAT,
  bms_max_curr FLOAT,
  bms_constant_volt FLOAT,
  bms_cell1_volt FLOAT,
  bms2_cell16_volt FLOAT,
  bms_gauge_rm FLOAT,
  bms_gauge_fcc FLOAT,
  bms_fw FLOAT,
  bms_delta_volt FLOAT,
  bms_cycle_count FLOAT,
  bms_soh FLOAT,
  bms_ic_current FLOAT,
  bms_mcu_version FLOAT,
  bms_gauge_version FLOAT,
  bms_fr_version FLOAT,

  -- BMS 2
  bms2_soc INT,
  bms2_battery_volt FLOAT,
  bms2_battery_curr FLOAT,
  bms2_battery_temp FLOAT,
  bms2_max_curr FLOAT,
  bms2_constant_volt FLOAT,
  bms2_cell1_volt FLOAT,
  bms2_gauge_rm FLOAT,
  bms2_gauge_fcc FLOAT,
  bms2_fw FLOAT,
  bms2_delta_volt FLOAT,
  bms2_cycle_count FLOAT,
  bms2_soh FLOAT,
  bms2_ic_current FLOAT,
  bms2_mcu_version FLOAT,
  bms2_gauge_version FLOAT,
  bms2_fr_version FLOAT,

  -- Solar 1
  solar1_status INT,
  solar1_fault_code INT,
  solar1_warning_code INT,
  solar1_bat_voltage FLOAT,
  solar1_pv1_voltage FLOAT,
  solar1_pv2_voltage FLOAT,
  solar1_buck1_current FLOAT,
  solar1_buck2_current FLOAT,
  solar1_pv1_charge_power FLOAT,
  solar1_pv2_charge_power FLOAT,
  solar1_hs1_temp FLOAT,
  solar1_hs2_temp FLOAT,
  solar1_epv1_today FLOAT,
  solar1_epv2_today FLOAT,
  solar1_epv1_total FLOAT,
  solar1_epv2_total FLOAT,

  -- Solar 2
  solar2_status INT,
  solar2_fault_code INT,
  solar2_warning_code INT,
  solar2_bat_voltage FLOAT,
  solar2_pv1_voltage FLOAT,
  solar2_pv2_voltage FLOAT,
  solar2_buck1_current FLOAT,
  solar2_buck2_current FLOAT,
  solar2_pv1_charge_power FLOAT,
  solar2_pv2_charge_power FLOAT,
  solar2_hs1_temp FLOAT,
  solar2_hs2_temp FLOAT,
  solar2_epv1_today FLOAT,
  solar2_epv2_today FLOAT,
  solar2_epv1_total FLOAT,
  solar2_epv2_total FLOAT,

  -- Flags and states
  system_status INT,
  fault_bit INT,
  warning_bit INT,
  fault_value INT,
  warning_value INT,
  device_type_code INT,
  check_step INT,
  production_line_mode INT,
  constant_power_ok_flag INT,
  bat_overcharge_flag INT,
  mppt_fan_speed FLOAT,
  inv_fan_speed FLOAT,
  load_percent FLOAT,
  work_time_total FLOAT,

  -- Misc
  solar_connect_ok_flag INT,
  solar_batvolt_consist_flag INT,
  solar_type_switch_state INT,
  solar_mode_switch_state INT,
  solar_address_switch_state INT,

  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
